# Generated by Django 3.1.7 on 2021-03-18 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0007_auto_20210314_0519'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userphone')),
            ],
        ),
    ]
