# Generated by Django 3.1.7 on 2021-03-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210322_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='shippingName',
            new_name='shipName',
        ),
    ]
