# Generated by Django 3.1.7 on 2021-03-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210322_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.PositiveBigIntegerField(),
        ),
    ]
