# Generated by Django 3.1.7 on 2021-03-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210322_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphone',
            name='age',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
        migrations.AddField(
            model_name='userphone',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others'), ('U', 'Unspecified')], default='Male', max_length=4),
        ),
        migrations.AlterField(
            model_name='address',
            name='phoneNo',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.PositiveIntegerField(),
        ),
    ]
