# Generated by Django 3.1.7 on 2021-03-27 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_orders_vieworder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cartId',
        ),
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userphone'),
        ),
    ]
