# Generated by Django 3.1.7 on 2021-03-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210327_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vieworder',
            name='cartId',
        ),
        migrations.AddField(
            model_name='vieworder',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vieworder',
            name='productName',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vieworder',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
