# Generated by Django 3.1.7 on 2021-03-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210327_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='vieworder',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
