# Generated by Django 3.1.7 on 2021-03-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_vieworder_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(default='kozhikode', max_length=200),
        ),
    ]
