# Generated by Django 3.1.7 on 2021-03-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_orders_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='landMark',
            field=models.CharField(default='blank', max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='phoneNo',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='pincode',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='shipName',
            field=models.CharField(default='blank', max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(default='blank', max_length=100),
        ),
    ]
