# Generated by Django 3.1.7 on 2021-03-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210327_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='delevered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
