# Generated by Django 3.1.7 on 2021-03-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210328_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='date_delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
