# Generated by Django 3.1.7 on 2021-04-07 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20210406_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponCode', models.CharField(max_length=20)),
                ('status', models.CharField(default='used', max_length=100)),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userphone')),
            ],
        ),
    ]
