# Generated by Django 3.1.7 on 2021-04-08 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_refferalcoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refferalcoupon',
            name='userK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userphone'),
        ),
    ]
