# Generated by Django 3.1.7 on 2021-03-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='productsImg',
            new_name='productImg',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='productsName',
            new_name='productName',
        ),
    ]
