# Generated by Django 3.1.7 on 2021-03-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_auto_20210312_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categoryPic',
            field=models.ImageField(upload_to='media/pics'),
        ),
        migrations.AlterField(
            model_name='products',
            name='productImg',
            field=models.ImageField(upload_to='media/img'),
        ),
    ]
