# Generated by Django 3.1.7 on 2021-04-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0007_auto_20210314_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='categoryDiscount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categories',
            name='categoryOffer',
            field=models.BooleanField(default=False),
        ),
    ]
