# Generated by Django 3.1.7 on 2021-04-06 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0010_auto_20210404_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponName', models.CharField(max_length=100)),
                ('couponCode', models.CharField(max_length=50, unique=True)),
                ('validFrom', models.DateTimeField()),
                ('validTo', models.DateTimeField()),
                ('discout', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField()),
            ],
        ),
    ]
