# Generated by Django 3.1.7 on 2021-04-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0011_coupons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupons',
            old_name='discout',
            new_name='discount',
        ),
        migrations.AlterField(
            model_name='coupons',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
